// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Dolittle")]
[assembly: AssemblyCopyrightAttribute("(C) 2008 - 2017 Dolittle")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0.0")]
