git clone https://github.com/dolittle/dolittle.github.io.git
xcopy Source\Documentation\_site dolittle.github.io /E /Y
cd dolittle.github.io
git add .
git commit -m "<-- Autogenerated : documentation updated -->"

