/*
@depends utils/stringExtensions.js
@depends utils/extend.js
@depends utils/namespace.js
@depends execution/Promise.js
@depends utils/isNumber.js
@depends utils/isArray.js
@depends utils/path.js
@depends utils/functionParser.js
@depends utils/assetsManager.js
@depends utils/dependencyResolver.js
@depends utils/dependencyResolvers.js
@depends utils/defaultDependencyResolver.js
@depends utils/WellKnownTypesDependencyResolver.js
@depends utils/Type.js
@depends utils/Singleton.js
@depends utils/Exception.js
@depends utils/exceptions.js
@depends utils/guid.js
@depends utils/hashString.js
@depends utils/Uri.js
@depends utils/namespaces.js
@depends utils/namespaceMappers.js
@depends utils/StringMapping.js
@depends utils/StringMapper.js
@depends utils/uriMappers.js
@depends validation/exceptions.js
@depends validation/ruleHandlers.js
@depends validation/Rule.js
@depends validation/Validator.js
@depends validation/validationSummaryFor.js
@depends validation/validationMessageFor.js
@depends validation/validation.js
@depends validation/validationService.js
@depends validation/required.js
@depends validation/minLength.js
@depends validation/maxLength.js
@depends validation/range.js
@depends validation/lessThan.js
@depends validation/greaterThan.js
@depends validation/email.js
@depends validation/regex.js
@depends commands/bindingHandlers.js
@depends commands/CommandCoordinator.js
@depends commands/commandValidationService.js
@depends commands/Command.js
@depends commands/CommandDescriptor.js
@depends commands/CommandResult.js
@depends commands/commandDependencyResolver.js
@depends read/queryService.js
@depends read/Query.js
@depends read/ReadModel.js
@depends read/ReadModelOf.js
@depends read/queryDependencyResolver.js
@depends read/queryService.js
@depends sagas/Saga.js
@depends sagas/sagaNarrator.js
@depends features/exceptions.js
@depends features/FeatureMapping.js
@depends features/featureMapper.js
@depends features/ViewModel.js
@depends features/ViewModelDefinition.js
@depends features/Feature.js
@depends features/featureManager.js
@depends features/featureBindingHandler.js
@depends messaging/Messenger.js
@depends messaging/observableMessage.js
@depends services/Service.js
@depends services/serviceDependencyResolver.js
@depends views/View.js
@depends views/ViewRenderer.js
@depends views/viewRenderers.js
@depends views/DataAttributeViewRenderer.js
@depends views/viewBindingHandler.js
@depends views/viewFactory.js
@depends views/viewLoader.js
@depends views/viewManager.js
@depends views/ViewModel.js
@depends views/viewModelManager.js
@depends views/ViewPathResolver.js
@depends views/viewPathResolvers.js
@depends views/UriMapperViewPathResolver.js
@depends navigation/NavigationFrame.js
@depends navigation/navigationFrames.js
@depends navigation/navigateTo.js
@depends navigation/navigationManager.js
@depends navigation/NavigationFrameViewRenderer.js
@depends navigation/observableQueryParameter.js
@depends utils/configure.js
*/