/*
@depends extensions/ArrayExtensions.js
@depends extensions/stringExtensions.js
@depends extensions/NodeListExtensions.js
@depends extensions/HTMLCollectionExtensions.js
@depends extensions/DateExtensions.js
@depends polyfills/ElementPolyfills.js
@depends utils/extend.js
@depends utils/namespace.js
@depends execution/Promise.js
@depends TimeSpan.js
@depends utils/isObject.js
@depends utils/isNumber.js
@depends utils/isArray.js
@depends utils/isString.js
@depends utils/isNull.js
@depends utils/isUndefined.js
@depends utils/isNullOrUndefined.js
@depends utils/isFunction.js
@depends utils/functionParser.js
@depends utils/assetsManager.js
@depends utils/dependencyResolver.js
@depends utils/dependencyResolvers.js
@depends utils/defaultDependencyResolver.js
@depends utils/WellKnownTypesDependencyResolver.js
@depends utils/DOMRootDependencyResolver.js
@depends utils/KnownArtifactTypesDependencyResolver.js
@depends utils/KnownArtifactInstancesDependencyResolver.js
@depends utils/guid.js
@depends utils/Type.js
@depends utils/Singleton.js
@depends utils/path.js
@depends utils/Exception.js
@depends utils/exceptions.js
@depends utils/hashString.js
@depends utils/Uri.js
@depends utils/namespaces.js
@depends utils/namespaceMappers.js
@depends utils/StringMapping.js
@depends utils/stringMappingFactory.js
@depends utils/StringMapper.js
@depends utils/uriMappers.js
@depends utils/server.js
@depends utils/systemClock.js
@depends io/fileType.js
@depends io/File.js
@depends io/fileFactory.js
@depends io/fileManager.js
@depends tasks/Task.js
@depends tasks/TaskHistoryEntry.js
@depends tasks/taskHistory.js
@depends tasks/Tasks.js
@depends tasks/tasksFactory.js
@depends tasks/HttpGetTask.js
@depends tasks/HttpPostTask.js
@depends tasks/LoadTask.js
@depends tasks/FileLoadTask.js
@depends tasks/ExecutionTask.js
@depends taskFactory.js
@depends validation/exceptions.js
@depends validation/ruleHandlers.js
@depends validation/Rule.js
@depends validation/Validator.js
@depends validation/validationSummaryFor.js
@depends validation/validationMessageFor.js
@depends validation/validation.js
@depends validation/required.js
@depends validation/minLength.js
@depends validation/maxLength.js
@depends validation/range.js
@depends validation/lessThan.js
@depends validation/lessThanOrEqual.js
@depends validation/greaterThan.js
@depends validation/greaterThanOrEqual.js
@depends validation/email.js
@depends validation/regex.js
@depends commands/bindingHandlers.js
@depends commands/HandleCommandTask.js
@depends commands/HandleCommandsTask.js
@depends commands/CommandCoordinator.js
@depends commands/commandValidationService.js
@depends commands/Command.js
@depends commands/CommandDescriptor.js
@depends commands/CommandResult.js
@depends commands/commandDependencyResolver.js
@depends commands/CommandSecurityContext.js
@depends commands/commandSecurityContextFactory.js
@depends commands/commandSecurityService.js
@depends commands/hasChanges.js
@depends interaction/Operation.js
@depends interaction/OperationContext.js
@depends interaction/OperationEntry.js
@depends interaction/operationEntryFactory.js
@depends interaction/Operations.js
@depends interaction/operationsFactory.js
@depends interaction/CommandOperation.js
@depends interaction/Action.js
@depends interaction/Trigger.js
@depends interaction/EventTrigger.js
@depends interaction/VisualState.js
@depends interaction/VisualStateGroup.js
@depends interaction/VisualStateManager.js
@depends interaction/VisualStateTransition.js
@depends interaction/VisualStateTransitionAction.js
@depends read/readModelMapper.js
@depends read/PagingInfo.js
@depends read/Queryable.js
@depends read/queryableFactory.js
@depends read/Query.js
@depends read/ReadModel.js
@depends read/ReadModelOf.js
@depends read/readModelOfDependencyResolver.js
@depends read/queryDependencyResolver.js
@depends read/QueryTask.js
@depends read/queryService.js
@depends sagas/Saga.js
@depends sagas/sagaNarrator.js
@depends messaging/Messenger.js
@depends messaging/messengerFactory.js
@depends messaging/observableMessage.js
@depends services/Service.js
@depends services/serviceDependencyResolver.js
@depends views/ComposeTask.js
@depends views/documentService.js
@depends views/View.js
@depends views/ViewRenderer.js
@depends views/viewRenderers.js
@depends views/DataAttributeViewRenderer.js
@depends views/viewFactory.js
@depends views/ViewLoadTask.js
@depends views/viewLoader.js
@depends views/viewManager.js
@depends views/ViewModel.js
@depends views/viewModelLoader.js
@depends views/ViewModelLoadTask.js
@depends views/viewModelManager.js
@depends views/PathResolver.js
@depends views/pathResolvers.js
@depends views/UriMapperPathResolver.js
@depends views/RelativePathResolver.js
@depends views/viewModelBindingHandler.js
@depends views/viewBindingHandler.js
@depends views/Region.js
@depends views/RegionDependencyResolver.js
@depends views/regionManager.js
@depends views/RegionDescriptor.js
@depends views/regionDescriptorManager.js
@depends views/RegionDescriptorDependencyResolver.js
@depends views/NamingRoot.js
@depends views/UIElement.js
@depends views/Control.js
@depends navigation/NavigationFrame.js
@depends navigation/navigationFrames.js
@depends navigation/navigateTo.js
@depends navigation/navigationManager.js
@depends navigation/NavigationFrameViewRenderer.js
@depends navigation/observableQueryParameter.js
@depends utils/configure.js
*/