/*
@depends utils/namespace.js
@depends utils/extend.js
@depends utils/guid.js
@depends utils/isNumber.js
@depends utils/hashString.js
@depends utils/TypeInfo.js
@depends validation/exceptions.js
@depends validation/ruleHandlers.js
@depends validation/Rule.js
@depends validation/Validator.js
@depends validation/validationMessageFor.js
@depends validation/validation.js
@depends validation/validationService.js
@depends validation/required.js
@depends validation/minLength.js
@depends validation/maxLength.js
@depends validation/range.js
@depends validation/lessThan.js
@depends validation/greaterThan.js
@depends validation/email.js
@depends validation/regex.js
@depends commands/bindingHandlers.js
@depends commands/CommandResult.js
@depends commands/Command.js
@depends commands/CommandDescriptor.js
@depends commands/commandCoordinator.js
@depends sagas/Saga.js
@depends sagas/sagaNarrator.js
@depends features/UriMapping.js
@depends features/uriMapper.js
@depends features/ViewModel.js
@depends features/ViewModelDefinition.js
@depends features/Feature.js
@depends features/featureManager.js
@depends features/loader.js
@depends navigation/navigateTo.js
@depends navigation/navigation.js
@depends messaging/messenger.js
*/